version: 1
builder:
  configs:
    - documentation_targets: [SwiftOSCIOCocoa]
      scheme: swift-osc-io-cocoa
    - platform: watchOS
      scheme: NOT_SUPPORTED
    - platform: linux
      target: NOT_SUPPORTED
    - platform: android
      target: NOT_SUPPORTED
    - platform: wasm
      target: NOT_SUPPORTED